-- 02_seed.sql | gerado a partir de inventario_loja.csv
-- ATENCAO: os precos abaixo sao valores iniciais por categoria. Ajuste antes de usar em producao.
INSERT INTO produto (nome, categoria, local, unidade, preco, estoque, observacao) VALUES
('Cartela de ovos brancos','Ovos','Balcao vitrine - topo','cartela',18.9,3,'~30 un por cartela (~90 ovos)'),
('Rosquinha / biscoito de polvilho (saco)','Panificacao','Balcao vitrine - topo','pacote',8.5,5,'Sacos transparentes grandes'),
('Pote de vidro com balas/pirulitos','Doces','Balcao vitrine - topo','pote',2.5,4,'Tampa verde'),
('Pao / biscoito em saco vermelho','Panificacao','Balcao vitrine - topo','pacote',8.5,8,'Empilhados'),
('Bolacha recheada (pacote azul)','Biscoitos','Balcao vitrine - topo','pacote',6.9,6,''),
('Caixas expositoras (chocolate/isqueiro/pilha)','Diversos','Balcao vitrine - topo','caixa',5.0,5,'Nao legivel no video'),
('Kerus Presunto','Salgadinho','Balcao vitrine - 1a fila','pacote',4.5,2,''),
('Kerus Requeijao','Salgadinho','Balcao vitrine - 1a fila','pacote',4.5,2,''),
('Kerus Queijo','Salgadinho','Balcao vitrine - 1a fila','pacote',4.5,1,''),
('Kerus Cebola e Salsa','Salgadinho','Balcao vitrine - 1a fila','pacote',4.5,2,''),
('Kerus Pipoca','Salgadinho','Balcao vitrine - 1a fila','pacote',4.5,5,'Embalagem vermelha'),
('Gulao Assado','Salgadinho','Balcao vitrine - 2a fila','pacote',4.5,9,'Variacoes vermelha/verde'),
('Gulao Pururuca','Salgadinho','Balcao vitrine - 2a fila','pacote',4.5,4,'Embalagem preta'),
('Batata Chips MIX Churrasco','Salgadinho','Balcao vitrine - 3a fila','pacote',4.5,7,''),
('Trento (display)','Doces','Balcao vitrine - prateleira','caixa',2.5,3,''),
('Mentos (display)','Doces','Balcao vitrine - prateleira','caixa',2.5,1,''),
('Bacia plastica com salgadinho/batata','Salgados a granel','Balcao vitrine - prateleira','bacia',3.0,6,'1 bacia com batata frita'),
('Pacotes brancos/azul marinho (biscoito/pao)','Biscoitos','Mesa verde 1','pacote',6.9,20,'Marca nao legivel'),
('Rosquinha / biscoito amanteigado','Biscoitos','Mesa verde 1','pacote',6.9,15,''),
('Pacotes vermelhos (biscoito/macarrao)','Biscoitos','Mesa verde 2','pacote',6.9,15,'Marca nao legivel'),
('Pacotes amarelos','Biscoitos','Mesa verde 2','pacote',6.9,6,''),
('Engradado AmBev (vazio/cheio)','Bebidas','Sob a mesa verde','engradado',9.9,3,''),
('Engradado vermelho','Bebidas','Sob a mesa verde','engradado',9.9,1,''),
('Galao/botijao plastico azul','Utilidades','Sob a mesa verde','unidade',15.0,1,''),
('Garrafas refrigerante/cerveja','Bebidas','Geladeira Imbera vertical','garrafa',9.9,15,'Reflexo no vidro - prateleiras altas vazias'),
('Tomate','Frutas','Hortifruti','unidade',7.9,45,'Caixa de madeira'),
('Maca','Frutas','Hortifruti','unidade',7.9,30,''),
('Batata','Legumes','Hortifruti','unidade',5.9,15,''),
('Pimentao / pepino','Legumes','Hortifruti','unidade',5.9,8,''),
('Limao','Frutas','Hortifruti','unidade',7.9,8,''),
('Laranja / tangerina','Frutas','Hortifruti','unidade',7.9,10,''),
('Abacate / fruta escura','Frutas','Hortifruti','unidade',7.9,6,''),
('Papel higienico Beli','Higiene','Hortifruti - prateleira','pacote',22.9,5,'Fardos + avulsos'),
('Bacia plastica verde','Utilidades','Hortifruti - prateleira','unidade',15.0,2,''),
('Saco de rosquinha (parte superior)','Panificacao','Hortifruti - prateleira','pacote',8.5,6,''),
('Garrafas (cachaca/licor/vinho)','Bebidas','Hortifruti - base','garrafa',9.9,10,''),
('Engradado vermelho com garrafas','Bebidas','Hortifruti - base','engradado',9.9,1,''),
('Caixa de bebida (Fumegante?)','Bebidas','Hortifruti - base','caixa',9.9,1,'Rotulo ilegivel'),
('Saco de racao farelada (branco)','Racao','Fundo / estoque','saco',89.9,2,'Escrito FARELADO'),
('Saco de racao para aves (verde)','Racao','Fundo / estoque','saco',89.9,3,'');
