-- 23_cadastro_fornecedor.sql — cadastro PÚBLICO de fornecedor + bairros atendidos.
-- Na tela /cadastro dá pra escolher "Sou empresa" ou "Sou fornecedor". O fornecedor
-- se cadastra na plataforma (nasce `pendente`, o super admin aprova) e marca os
-- bairros que atende. Cidade inicial do lançamento: Conselheiro Lafaiete, MG.
-- Espelhado em MIGRACOES_IDEMPOTENTES (src/lib/db.ts). NÃO vai pro desktop
-- (é recurso de plataforma / multi-tenant).

CREATE TABLE IF NOT EXISTS bairro (
  id     bigserial PRIMARY KEY,
  cidade text NOT NULL,
  uf     text NOT NULL DEFAULT 'MG',
  nome   text NOT NULL,
  UNIQUE (cidade, uf, nome)
);

CREATE TABLE IF NOT EXISTS fornecedor_publico (
  id                bigserial PRIMARY KEY,
  nome              text NOT NULL,
  documento         text,
  telefone          text,
  telefone_whatsapp boolean NOT NULL DEFAULT false,
  endereco          text,
  observacao        text,
  pix_chave         text,
  email             text NOT NULL UNIQUE,
  senha_hash        text,
  cidade            text NOT NULL,
  situacao          text NOT NULL DEFAULT 'pendente',
  criado_em         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS fornecedor_publico_bairro (
  fornecedor_publico_id bigint NOT NULL REFERENCES fornecedor_publico(id) ON DELETE CASCADE,
  bairro_id             bigint NOT NULL REFERENCES bairro(id) ON DELETE CASCADE,
  PRIMARY KEY (fornecedor_publico_id, bairro_id)
);

-- bairros de Conselheiro Lafaiete (fonte: cepbrasil.com, set/2026)
INSERT INTO bairro (cidade, uf, nome) VALUES
     ('Conselheiro Lafaiete', 'MG', 'Albertina'),
     ('Conselheiro Lafaiete', 'MG', 'Albinópolis'),
     ('Conselheiro Lafaiete', 'MG', 'Almeidas'),
     ('Conselheiro Lafaiete', 'MG', 'Alvorada'),
     ('Conselheiro Lafaiete', 'MG', 'Amaro Ribeiro'),
     ('Conselheiro Lafaiete', 'MG', 'Angélica'),
     ('Conselheiro Lafaiete', 'MG', 'Arcádia'),
     ('Conselheiro Lafaiete', 'MG', 'Área Rural'),
     ('Conselheiro Lafaiete', 'MG', 'Areal'),
     ('Conselheiro Lafaiete', 'MG', 'Barreira'),
     ('Conselheiro Lafaiete', 'MG', 'Bela Vista'),
     ('Conselheiro Lafaiete', 'MG', 'Bellavinha'),
     ('Conselheiro Lafaiete', 'MG', 'Belvedere'),
     ('Conselheiro Lafaiete', 'MG', 'Bom Pastor'),
     ('Conselheiro Lafaiete', 'MG', 'Buarque de Macedo'),
     ('Conselheiro Lafaiete', 'MG', 'Cachoeira'),
     ('Conselheiro Lafaiete', 'MG', 'Campo Alegre'),
     ('Conselheiro Lafaiete', 'MG', 'Carijós'),
     ('Conselheiro Lafaiete', 'MG', 'Centro'),
     ('Conselheiro Lafaiete', 'MG', 'Chapada'),
     ('Conselheiro Lafaiete', 'MG', 'Cidade Jardim'),
     ('Conselheiro Lafaiete', 'MG', 'Cidade Nova'),
     ('Conselheiro Lafaiete', 'MG', 'Copacabana'),
     ('Conselheiro Lafaiete', 'MG', 'Distrito Industrial'),
     ('Conselheiro Lafaiete', 'MG', 'Expedicionários'),
     ('Conselheiro Lafaiete', 'MG', 'Fonte Grande'),
     ('Conselheiro Lafaiete', 'MG', 'Funcionários'),
     ('Conselheiro Lafaiete', 'MG', 'Gagé'),
     ('Conselheiro Lafaiete', 'MG', 'Gigante'),
     ('Conselheiro Lafaiete', 'MG', 'Granja das Hortênsias'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim América'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim Canadá'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim das Flores'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim do Sol'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim dos Cristais'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim Eldorado'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim Europa'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim Inconfidentes'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim Monte Verde'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim São Geraldo'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim Vila Rica'),
     ('Conselheiro Lafaiete', 'MG', 'Jardim Vitória'),
     ('Conselheiro Lafaiete', 'MG', 'JK'),
     ('Conselheiro Lafaiete', 'MG', 'Lima Dias'),
     ('Conselheiro Lafaiete', 'MG', 'Lourdes'),
     ('Conselheiro Lafaiete', 'MG', 'Manoel Corrêa'),
     ('Conselheiro Lafaiete', 'MG', 'Manoel de Paula'),
     ('Conselheiro Lafaiete', 'MG', 'Moinhos'),
     ('Conselheiro Lafaiete', 'MG', 'Monte Cristo'),
     ('Conselheiro Lafaiete', 'MG', 'Morada do Sol'),
     ('Conselheiro Lafaiete', 'MG', 'Morro da Mina'),
     ('Conselheiro Lafaiete', 'MG', 'Museu'),
     ('Conselheiro Lafaiete', 'MG', 'Nossa Senhora da Guia'),
     ('Conselheiro Lafaiete', 'MG', 'Novo Horizonte'),
     ('Conselheiro Lafaiete', 'MG', 'Oscar Corrêa'),
     ('Conselheiro Lafaiete', 'MG', 'Ouro Verde'),
     ('Conselheiro Lafaiete', 'MG', 'Parque Bandeirantes'),
     ('Conselheiro Lafaiete', 'MG', 'Parque Cidade'),
     ('Conselheiro Lafaiete', 'MG', 'Parque das Acácias'),
     ('Conselheiro Lafaiete', 'MG', 'Parque Dom Bosco'),
     ('Conselheiro Lafaiete', 'MG', 'Parque dos Ferroviários'),
     ('Conselheiro Lafaiete', 'MG', 'Parque Montreal'),
     ('Conselheiro Lafaiete', 'MG', 'Parque Recanto da Hípica'),
     ('Conselheiro Lafaiete', 'MG', 'Paulo VI'),
     ('Conselheiro Lafaiete', 'MG', 'Progresso'),
     ('Conselheiro Lafaiete', 'MG', 'Queluz'),
     ('Conselheiro Lafaiete', 'MG', 'Quinta das Flores'),
     ('Conselheiro Lafaiete', 'MG', 'Quintas do Imperador'),
     ('Conselheiro Lafaiete', 'MG', 'Quintas do Sol'),
     ('Conselheiro Lafaiete', 'MG', 'Rancho Novo'),
     ('Conselheiro Lafaiete', 'MG', 'Real de Queluz'),
     ('Conselheiro Lafaiete', 'MG', 'Recanto dos Colibris'),
     ('Conselheiro Lafaiete', 'MG', 'Rezende'),
     ('Conselheiro Lafaiete', 'MG', 'Rochedo'),
     ('Conselheiro Lafaiete', 'MG', 'Rosário'),
     ('Conselheiro Lafaiete', 'MG', 'Sagrada Família'),
     ('Conselheiro Lafaiete', 'MG', 'Sagrado Coração de Jesus'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Clara'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Cruz'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Efigênia'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Fé'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Luzia'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Maria'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Matilde'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Rosa'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Tereza'),
     ('Conselheiro Lafaiete', 'MG', 'Santa Terezinha'),
     ('Conselheiro Lafaiete', 'MG', 'Santo Agostinho'),
     ('Conselheiro Lafaiete', 'MG', 'Santo Antônio'),
     ('Conselheiro Lafaiete', 'MG', 'São Benedito'),
     ('Conselheiro Lafaiete', 'MG', 'São Dimas'),
     ('Conselheiro Lafaiete', 'MG', 'São Gonçalo do Brandão'),
     ('Conselheiro Lafaiete', 'MG', 'São João'),
     ('Conselheiro Lafaiete', 'MG', 'São Jorge'),
     ('Conselheiro Lafaiete', 'MG', 'São José'),
     ('Conselheiro Lafaiete', 'MG', 'São Judas Tadeu'),
     ('Conselheiro Lafaiete', 'MG', 'São Lucas'),
     ('Conselheiro Lafaiete', 'MG', 'São Marcos'),
     ('Conselheiro Lafaiete', 'MG', 'São Sebastião'),
     ('Conselheiro Lafaiete', 'MG', 'São Vicente de Paula'),
     ('Conselheiro Lafaiete', 'MG', 'Satélite'),
     ('Conselheiro Lafaiete', 'MG', 'Siderúrgico'),
     ('Conselheiro Lafaiete', 'MG', 'Sion'),
     ('Conselheiro Lafaiete', 'MG', 'Tamareiras'),
     ('Conselheiro Lafaiete', 'MG', 'Tiradentes'),
     ('Conselheiro Lafaiete', 'MG', 'Topázio'),
     ('Conselheiro Lafaiete', 'MG', 'Triângulo'),
     ('Conselheiro Lafaiete', 'MG', 'União'),
     ('Conselheiro Lafaiete', 'MG', 'Vila das Andorinhas'),
     ('Conselheiro Lafaiete', 'MG', 'Vila Veneza')
   ON CONFLICT (cidade, uf, nome) DO NOTHING;
